name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: srv-obin-ch_ubuntu-latest
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - name: Install dependencies
        run: bun install

      - name: Create tags
        uses: https://github.com/changesets/action@v1
        id: changesets
        with:
          publish: bun run tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tags
        run: git push --follow-tags

      - name: Plan container images to publish
        id: images
        run: |
          possible_targets=$(git ls-files -- '**/Dockerfile' \
            | while read -r f; do dir=$(dirname "$f"); if [ -f "$dir/package.json" ]; then jq -r '.name' "$dir/package.json"; fi; done \
            | jq -R -s 'split("\n") | map(select(length>0))')
          published_packages='${{ steps.changesets.outputs.publishedPackages }}'
          targets=$(echo $published_packages | jq -c --argjson possible_targets "$possible_targets" 'map(select(.name == $possible_targets[]))')
          echo "images=$targets" >> $GITHUB_OUTPUT
          echo "Published packages: $published_packages"
          echo "Images to build: $targets"
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      images: ${{ steps.images.outputs.images }}

  build-base-image:
    name: Build base image
    runs-on: srv-obin-ch_ubuntu-latest
    needs: publish
    if: needs.publish.outputs.published == 'true'
    outputs:
      base-tag: ${{ steps.set-base-tag.outputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host

      - name: Log into registry codeberg.org
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Set base image tag
        id: set-base-tag
        run: |
          TAG="codeberg.org/fairaccess/fairaccess-base:${{ github.sha }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Building base image with tag: $TAG"

      - name: Build and push base image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f Dockerfile.root \
            -t ${{ steps.set-base-tag.outputs.tag }} \
            . \
            --push
          echo "Base image built and pushed: ${{ steps.set-base-tag.outputs.tag }}"

  build-and-publish-images:
    name: Build and publish images
    runs-on: srv-obin-ch_ubuntu-latest
    needs: [publish, build-base-image]
    if: needs.publish.outputs.published == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host

      - name: Log into registry codeberg.org
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and publish all images
        env:
          IMAGES_JSON: ${{ needs.publish.outputs.images }}
          BASE_IMAGE: ${{ needs.build-base-image.outputs.base-tag }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail

          # Parse images JSON and iterate
          echo "Images to build: $IMAGES_JSON"

          echo "$IMAGES_JSON" | jq -c '.[]' | while read -r package; do
            PACKAGE_NAME=$(echo "$package" | jq -r '.name')
            PACKAGE_VERSION=$(echo "$package" | jq -r '.version')

            echo ""
            echo "======================================================================"
            echo "Processing package: $PACKAGE_NAME version $PACKAGE_VERSION"
            echo "======================================================================"

            # Find package directory
            PACKAGE_DIR=$(git ls-files -- '**/package.json' | while read -r f; do
              name=$(jq -r '.name' "$f")
              if [ "$name" = "$PACKAGE_NAME" ]; then
                dirname "$f"
              fi
            done | head -n1)

            if [ -z "$PACKAGE_DIR" ]; then
              echo "No directory found for $PACKAGE_NAME. Skipping."
              continue
            fi

            if [ ! -f "$PACKAGE_DIR/Dockerfile" ]; then
              echo "No Dockerfile for $PACKAGE_NAME in $PACKAGE_DIR. Skipping."
              continue
            fi

            echo "Found Dockerfile: $PACKAGE_DIR/Dockerfile"

            # Generate tags
            MAJOR=$(echo "$PACKAGE_VERSION" | cut -d. -f1)
            MINOR=$(echo "$PACKAGE_VERSION" | cut -d. -f2)
            SHORTNAME=$(echo "$PACKAGE_NAME" | cut -d/ -f2)
            BASENAME="codeberg.org/fairaccess/fairaccess-$SHORTNAME"

            echo "Building with tags:"
            echo " - $BASENAME:latest"
            echo " - $BASENAME:$GITHUB_SHA"
            echo " - $BASENAME:$PACKAGE_VERSION"
            echo " - $BASENAME:$MAJOR"
            echo " - $BASENAME:$MAJOR.$MINOR"

            # Build and push
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --build-arg BASE_IMAGE="$BASE_IMAGE" \
              -t "$BASENAME:latest" \
              -t "$BASENAME:$GITHUB_SHA" \
              -t "$BASENAME:$PACKAGE_VERSION" \
              -t "$BASENAME:$MAJOR" \
              -t "$BASENAME:$MAJOR.$MINOR" \
              -f "$PACKAGE_DIR/Dockerfile" \
              "$PACKAGE_DIR" \
              --push

            echo "Image build & push complete for $PACKAGE_NAME:$PACKAGE_VERSION"
          done

          echo ""
          echo "All images built and pushed successfully!"
