networks:
  fairaccess:
    name: fairaccess
    external: true
  proxy:
    name: proxy
    external: true

volumes:
  database:
    name: database
    driver: local

services:
  core-migrate:
    image: codeberg.org/fairaccess/fairaccess-core:0.0.45
    restart: "no"
    volumes:
      - database:/database
    environment:
      DATABASE_URL: /database/fairaccess.db
    command: ["migrate"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=fairaccess"
    networks:
      - fairaccess

  core:
    image: codeberg.org/fairaccess/fairaccess-core:0.0.45
    restart: unless-stopped
    depends_on:
      core-migrate:
        condition: service_completed_successfully
    volumes:
      - database:/database
    environment:
      DATABASE_URL: /database/fairaccess.db
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: https://fairaccess.ch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=fairaccess"
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`fairaccess.ch`)"
      - "traefik.http.routers.core.entrypoints=http,https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      - "traefik.http.routers.core.middlewares=redirect-https"
      - "traefik.http.routers.core.tls=true"
      - "traefik.http.routers.core.tls.certresolver=letsencrypt"
      - "traefik.http.services.core.loadbalancer.server.port=3000"
    networks:
      - proxy
      - fairaccess

  watchtower:
    image: docker.io/nickfedor/watchtower:1.14.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_TOKEN}
      WATCHTOWER_SCOPE: "fairaccess"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.fairaccess.ch`)"
      - "traefik.http.routers.watchtower.entrypoints=https"
      - "traefik.http.routers.watchtower.tls=true"
      - "traefik.http.routers.watchtower.tls.certresolver=letsencrypt"
      - "traefik.http.services.watchtower.loadbalancer.server.port=8080"
    networks:
      - proxy
